// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1dde9e7d-b88c-4a2d-a40c-2fb760f48f45",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YKbeEHItj",
    "aws_user_pools_web_client_id": "39vvj1o70uf77hml8n33gim5qk",
    "oauth": {
        "domain": "littystyles-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "littystyles://",
        "redirectSignOut": "littystyles://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://y2xlmiz6wzfknpxbwdsyp3ufhy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "apiForLambda",
            "endpoint": "https://n1fjyuwlz5.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "littystyle-dev-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d38tvovvwgbq83.cloudfront.net",
    "aws_user_files_s3_bucket": "littystylesb114547-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
