platform :ios, '10.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'app' do
  use_unimodules!
  config = use_native_modules!
  use_react_native!(path: config['reactNativePath'])
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  #pod 'RNFirebase', :path => '../node_modules/react-native-unimodules'
  pod 'Firebase/Messaging', '<6'
  pod 'Firebase', '<6'
  pod 'Firebase/Analytics', '<6'
  pod 'Firebase/Core', '<6'
  pod 'FirebaseMessaging', '<6'

  #use_flipper!({'Flipper' => '0.82.0'}) # should match the version of your Flipper client app
  #pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  post_install do |installer|
    flipper_post_install(installer)
  end
end